# Logistic Regression Preprocessing Benchmark
Non-AdaBoost logistic baseline using the shared preprocessing benchmark framework.

In [1]:
from preprocessing_benchmark_framework import (
    print_best_model_metrics,
    run_preprocessing_benchmark,
)

results_df, strategy_artifacts, top_per_metric, top_scores_df, top_combined, _ = run_preprocessing_benchmark(
    model_type='logistic',
    variant='default',
    output_dir_name='logistic',
    run_randomized=True,
    run_explicit=False,
    n_random_iterations_override=2,
    use_imbalance_options=False,
    balance_classes_before_training=True,
    total_threads=16,
    num_current_notebooks=4,
    numeric_transformer_names=['standard_scaler'],
    add_polynomial=True,
    score_priority=['recall', 'precission', 'accuracy', 'f1', 'ROC-AUC'],
    top_n=25,
    metrics_to_save=['recall', 'precision', 'accuracy', 'f1', 'roc_auc'],
)

Saved recall best model -> /home/lelandmesford/Projects/HospitalClinicalDeterioration/logistic/logistic_outliers_True_robust_scaler_ordinalencoder_best_recall.joblib
Saved precision best model -> /home/lelandmesford/Projects/HospitalClinicalDeterioration/logistic/logistic_outliers_False_sqrt_transformer_onehotencoder_best_precision.joblib
Saved accuracy best model -> /home/lelandmesford/Projects/HospitalClinicalDeterioration/logistic/logistic_outliers_False_sqrt_transformer_ordinalencoder_best_accuracy.joblib
Saved f1 best model -> /home/lelandmesford/Projects/HospitalClinicalDeterioration/logistic/logistic_outliers_False_sqrt_transformer_onehotencoder_best_f1.joblib
Saved roc_auc best model -> /home/lelandmesford/Projects/HospitalClinicalDeterioration/logistic/logistic_outliers_True_robust_scaler_onehotencoder_best_roc_auc.joblib

In [2]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None) 


priority = ['recall', 'precision', 'accuracy', 'f1', 'roc_auc']

print_best_model_metrics(results_df, metrics_to_show=priority)

print('Top score per metric (top-1 by metric):')
display(top_scores_df)

print('Combined top-N shortlist (deduplicated, sorted by ROC-AUC):')
display(top_combined)

Best model by test_recall:
config=num=robust_scaler, cat=ordinalencoder, outliers=True, squared=True, cubed=True
best_params={'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.838      0.301     0.875 0.443    0.938
   test   0.840      0.303     0.877 0.445    0.939

Best model by test_precision:
config=num=sqrt_transformer, cat=onehotencoder, outliers=False, squared=True, cubed=True
best_params={'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.835      0.305     0.878 0.446    0.938
   test   0.836      0.304     0.877 0.446    0.938

Best model by test_accuracy:
config=num=sqrt_transformer, cat=ordinalencoder, outliers=False, squared=True, cubed=True
best_params={'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.835      0.303     0.877 0.445    0.938
   test   0.835      0.303     0.877 0.444    0.938

Best model by test_f1:
config=num=sqrt_transformer, cat=onehotencoder, outliers=False, squared=True, cubed=True
best_params={'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.835      0.305     0.878 0.446    0.938
   test   0.836      0.304     0.877 0.446    0.938

Best model by test_roc_auc:
config=num=robust_scaler, cat=onehotencoder, outliers=True, squared=True, cubed=True
best_params={'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.838      0.301     0.875 0.443    0.938
   test   0.839      0.303     0.877 0.446    0.939
Top score per metric (top-1 by metric):

,metric,run_id,numeric_transformer,categorical_transformer,outliers_clipped,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,recall,run_061,robust_scaler,onehotencoder,True,True,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.838,0.301,0.875,0.443,0.938,0.840,0.303,0.876,0.445,0.938,0.835,0.192,0.802,0.313,0.857
1,precision,run_094,sqrt_transformer,onehotencoder,False,False,True,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,54,3,61,0.835,0.305,0.878,0.446,0.938,0.836,0.304,0.877,0.446,0.938,0.833,0.194,0.804,0.315,0.857
2,accuracy,run_072,sqrt_transformer,ordinalencoder,False,False,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,39,0.833,0.302,0.877,0.444,0.938,0.835,0.303,0.877,0.444,0.938,0.832,0.193,0.803,0.314,0.857
3,f1,run_085,robust_scaler,onehotencoder,True,True,True,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,54,3,61,0.838,0.301,0.875,0.443,0.938,0.839,0.303,0.877,0.446,0.939,0.835,0.192,0.801,0.313,0.857
4,roc_auc,run_037,robust_scaler,onehotencoder,True,True,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.838,0.301,0.875,0.443,0.938,0.838,0.303,0.876,0.445,0.939,0.837,0.193,0.802,0.313,0.857

Combined top-N shortlist (deduplicated, sorted by ROC-AUC):

,run_id,numeric_transformer,categorical_transformer,outliers_clipped,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,run_087,robust_scaler,ordinalencoder,True,True,True,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,54,3,57,0.838,0.301,0.875,0.443,0.938,0.840,0.303,0.877,0.445,0.939,0.835,0.192,0.801,0.313,0.857
1,run_085,robust_scaler,onehotencoder,True,True,True,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,54,3,61,0.838,0.301,0.875,0.443,0.938,0.839,0.303,0.877,0.446,0.939,0.835,0.192,0.801,0.313,0.857
2,run_063,robust_scaler,ordinalencoder,True,True,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,39,0.837,0.301,0.876,0.443,0.938,0.839,0.302,0.876,0.445,0.939,0.834,0.192,0.802,0.313,0.857
3,run_039,robust_scaler,ordinalencoder,True,True,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,39,0.837,0.301,0.876,0.443,0.938,0.838,0.303,0.876,0.445,0.939,0.835,0.192,0.802,0.313,0.857
4,run_037,robust_scaler,onehotencoder,True,True,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.838,0.301,0.875,0.443,0.938,0.838,0.303,0.876,0.445,0.939,0.837,0.193,0.802,0.313,0.857
5,run_061,robust_scaler,onehotencoder,True,True,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.838,0.301,0.875,0.443,0.938,0.840,0.303,0.876,0.445,0.938,0.835,0.192,0.802,0.313,0.857
6,run_079,power_transformer,ordinalencoder,True,True,True,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,54,3,57,0.836,0.297,0.873,0.438,0.937,0.838,0.298,0.874,0.440,0.938,0.835,0.191,0.800,0.311,0.857
7,run_047,sqrt_transformer,ordinalencoder,True,True,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,39,0.834,0.300,0.875,0.441,0.937,0.836,0.302,0.876,0.444,0.938,0.832,0.192,0.802,0.313,0.857
8,run_045,sqrt_transformer,onehotencoder,True,True,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.835,0.300,0.875,0.441,0.937,0.836,0.302,0.876,0.444,0.938,0.834,0.193,0.802,0.313,0.857
9,run_095,sqrt_transformer,ordinalencoder,True,True,True,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,54,3,57,0.834,0.302,0.876,0.444,0.937,0.835,0.303,0.877,0.445,0.938,0.831,0.193,0.803,0.313,0.856
10,run_077,power_transformer,onehotencoder,True,True,True,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,54,3,61,0.836,0.297,0.873,0.438,0.937,0.838,0.299,0.875,0.441,0.938,0.836,0.192,0.801,0.312,0.857
11,run_046,sqrt_transformer,onehotencoder,False,False,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.835,0.300,0.875,0.442,0.938,0.837,0.301,0.876,0.443,0.938,0.834,0.193,0.802,0.313,0.857
12,run_048,sqrt_transformer,ordinalencoder,False,False,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,39,0.836,0.301,0.876,0.443,0.938,0.837,0.301,0.876,0.443,0.938,0.835,0.193,0.802,0.314,0.857
13,run_094,sqrt_transformer,onehotencoder,False,False,True,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,54,3,61,0.835,0.305,0.878,0.446,0.938,0.836,0.304,0.877,0.446,0.938,0.833,0.194,0.804,0.315,0.857
14,run_070,sqrt_transformer,onehotencoder,False,False,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.835,0.302,0.876,0.443,0.938,0.837,0.302,0.876,0.444,0.938,0.833,0.193,0.803,0.313,0.857
15,run_093,sqrt_transformer,onehotencoder,True,True,True,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,54,3,61,0.835,0.301,0.876,0.442,0.937,0.836,0.303,0.877,0.445,0.938,0.833,0.193,0.803,0.313,0.856
16,run_072,sqrt_transformer,ordinalencoder,False,False,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,39,0.833,0.302,0.877,0.444,0.938,0.835,0.303,0.877,0.444,0.938,0.832,0.193,0.803,0.314,0.857
17,run_069,sqrt_transformer,onehotencoder,True,True,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.834,0.299,0.875,0.441,0.937,0.837,0.301,0.876,0.443,0.938,0.834,0.193,0.802,0.313,0.856
18,run_096,sqrt_transformer,ordinalencoder,False,False,True,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,54,3,57,0.835,0.303,0.877,0.445,0.938,0.835,0.303,0.877,0.444,0.938,0.834,0.194,0.803,0.314,0.857
19,run_054,power_transformer,onehotencoder,False,False,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.837,0.293,0.871,0.434,0.936,0.838,0.296,0.873,0.437,0.937,0.836,0.190,0.799,0.310,0.855
20,run_029,power_transformer,onehotencoder,True,True,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.836,0.296,0.873,0.437,0.937,0.838,0.298,0.874,0.439,0.937,0.834,0.191,0.800,0.311,0.857
21,run_031,power_transformer,ordinalencoder,True,True,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,39,0.836,0.295,0.872,0.436,0.937,0.839,0.298,0.874,0.439,0.937,0.833,0.190,0.799,0.310,0.856
22,run_055,power_transformer,ordinalencoder,True,True,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,39,0.836,0.296,0.873,0.437,0.937,0.838,0.298,0.874,0.439,0.937,0.835,0.191,0.800,0.311,0.857
23,run_013,robust_scaler,onehotencoder,True,True,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,25,0.834,0.298,0.874,0.439,0.937,0.833,0.300,0.875,0.441,0.937,0.834,0.191,0.801,0.311,0.856
24,run_056,power_transformer,ordinalencoder,False,False,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,39,0.836,0.293,0.871,0.434,0.936,0.837,0.296,0.873,0.437,0.937,0.836,0.190,0.799,0.310,0.855
25,run_053,power_transformer,onehotencoder,True,True,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.836,0.296,0.873,0.437,0.937,0.837,0.298,0.874,0.440,0.937,0.834,0.191,0.800,0.311,0.857
26,run_032,power_transformer,ordinalencoder,False,False,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,39,0.836,0.293,0.871,0.434,0.936,0.837,0.295,0.873,0.437,0.937,0.836,0.190,0.799,0.310,0.855
27,run_030,power_transformer,onehotencoder,False,False,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.837,0.294,0.871,0.435,0.936,0.837,0.296,0.873,0.437,0.937,0.835,0.190,0.799,0.310,0.855
28,run_008,power_transformer,ordinalencoder,False,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,21,0.837,0.294,0.872,0.435,0.936,0.837,0.296,0.873,0.437,0.937,0.837,0.191,0.799,0.311,0.855
29,run_005,power_transformer,onehotencoder,True,True,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,25,0.837,0.295,0.872,0.436,0.937,0.837,0.297,0.873,0.438,0.937,0.836,0.191,0.799,0.311,0.856
30,run_007,power_transformer,ordinalencoder,True,True,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,21,0.836,0.295,0.872,0.436,0.937,0.837,0.296,0.873,0.438,0.937,0.835,0.191,0.799,0.310,0.856
31,run_006,power_transformer,onehotencoder,False,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,25,0.837,0.294,0.872,0.435,0.936,0.836,0.296,0.873,0.437,0.937,0.835,0.190,0.799,0.310,0.855
32,run_015,robust_scaler,ordinalencoder,True,True,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,21,0.834,0.298,0.874,0.439,0.937,0.833,0.300,0.875,0.441,0.937,0.834,0.191,0.801,0.311,0.855
33,run_014,robust_scaler,onehotencoder,False,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,25,0.834,0.299,0.875,0.440,0.937,0.834,0.301,0.876,0.442,0.937,0.834,0.192,0.802,0.312,0.855
34,run_016,robust_scaler,ordinalencoder,False,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,21,0.833,0.299,0.875,0.441,0.937,0.834,0.301,0.876,0.443,0.937,0.834,0.192,0.801,0.312,0.855
35,run_022,sqrt_transformer,onehotencoder,False,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,25,0.833,0.292,0.871,0.433,0.935,0.839,0.295,0.872,0.437,0.936,0.834,0.190,0.798,0.309,0.854
36,run_024,sqrt_transformer,ordinalencoder,False,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,21,0.833,0.293,0.872,0.434,0.935,0.837,0.295,0.872,0.436,0.936,0.833,0.190,0.799,0.309,0.854
37,run_023,sqrt_transformer,ordinalencoder,True,True,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,21,0.834,0.292,0.871,0.433,0.935,0.837,0.294,0.872,0.435,0.936,0.833,0.189,0.798,0.308,0.854
38,run_062,robust_scaler,onehotencoder,False,False,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.816,0.298,0.876,0.437,0.928,0.818,0.299,0.876,0.438,0.930,0.812,0.190,0.802,0.308,0.848