# AdaBoost (Perceptron Base Estimator) Preprocessing Benchmark

In [ ]:
from preprocessing_benchmark_framework import (
    print_best_model_metrics,
    run_preprocessing_benchmark,
)

results_df, strategy_artifacts, top_per_metric, top_scores_df, top_combined, _ = run_preprocessing_benchmark(
    model_type='adaboost',
    variant='perceptron',
    output_dir_name='adaboost_perceptron',
    run_randomized=True,
    run_explicit=False,
    n_random_iterations_override=2,
    use_imbalance_options=False,
    balance_classes_before_training=True,
    total_threads=16,
    num_current_notebooks=4,
    iqr_multiplier=3.0,
    numeric_transformer_names=['standard_scaler'],
    add_polynomial=True,
    score_priority=['recall', 'precision', 'accuracy', 'f1', 'ROC-AUC'],
    top_n=25,
    metrics_to_save=[],
)

In [2]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_columns", None)   # show all columns
pd.set_option("display.max_colwidth", None) # show full column content

priority = ['recall', 'precision', 'accuracy', 'f1', 'roc_auc']

print_best_model_metrics(results_df, metrics_to_show=priority)

print('Top score per metric (top-1 by metric):')
display(top_scores_df)

print('Combined top-N shortlist (deduplicated, sorted by ROC-AUC):')
display(top_combined)

Best model by test_recall:
config=num=log_transformer, cat=ordinalencoder, outliers=False, squared=True, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.945      0.150     0.681 0.259    0.895
   test   0.945      0.151     0.683 0.260    0.895

Best model by test_precision:
config=num=sqrt_transformer, cat=ordinalencoder, outliers=True, squared=True, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.611      0.685      0.96 0.646    0.826
   test   0.610      0.680      0.96 0.643    0.825

Best model by test_accuracy:
config=num=sqrt_transformer, cat=ordinalencoder, outliers=True, squared=True, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.611      0.685      0.96 0.646    0.826
   test   0.610      0.680      0.96 0.643    0.825

Best model by test_f1:
config=num=sqrt_transformer, cat=ordinalencoder, outliers=True, squared=True, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.611      0.685      0.96 0.646    0.826
   test   0.610      0.680      0.96 0.643    0.825

Best model by test_roc_auc:
config=num=log_transformer, cat=ordinalencoder, outliers=True, squared=True, cubed=True
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.821      0.283     0.866 0.421    0.930
   test   0.821      0.284     0.867 0.422    0.931
Top score per metric (top-1 by metric):

,metric,run_id,numeric_transformer,categorical_transformer,outliers_clipped,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,recall,run_028,log_transformer,ordinalencoder,False,False,True,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,39,0.945,0.150,0.681,0.259,0.895,0.945,0.151,0.683,0.260,0.895,0.944,0.121,0.625,0.214,0.821
1,precision,run_047,sqrt_transformer,ordinalencoder,True,True,True,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,39,0.611,0.685,0.960,0.646,0.826,0.610,0.680,0.960,0.643,0.825,0.612,0.252,0.881,0.357,0.781
2,accuracy,run_047,sqrt_transformer,ordinalencoder,True,True,True,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,39,0.611,0.685,0.960,0.646,0.826,0.610,0.680,0.960,0.643,0.825,0.612,0.252,0.881,0.357,0.781
3,f1,run_047,sqrt_transformer,ordinalencoder,True,True,True,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,39,0.611,0.685,0.960,0.646,0.826,0.610,0.680,0.960,0.643,0.825,0.612,0.252,0.881,0.357,0.781
4,roc_auc,run_051,log_transformer,ordinalencoder,True,True,False,True,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",3.0,36,3,39,0.825,0.288,0.869,0.427,0.930,0.831,0.291,0.871,0.432,0.931,0.824,0.188,0.797,0.306,0.861

Combined top-N shortlist (deduplicated, sorted by ROC-AUC):

,run_id,numeric_transformer,categorical_transformer,outliers_clipped,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,run_051,log_transformer,ordinalencoder,True,True,False,True,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",3.0,36,3,39,0.825,0.288,0.869,0.427,0.930,0.831,0.291,0.871,0.432,0.931,0.824,0.188,0.797,0.306,0.861
1,run_075,log_transformer,ordinalencoder,True,True,True,True,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",3.0,54,3,57,0.821,0.283,0.866,0.421,0.930,0.821,0.284,0.867,0.422,0.931,0.828,0.187,0.796,0.305,0.854
2,run_026,log_transformer,onehotencoder,False,False,True,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",3.0,36,3,43,0.848,0.255,0.845,0.393,0.928,0.853,0.258,0.846,0.396,0.930,0.849,0.175,0.775,0.290,0.852
3,run_023,sqrt_transformer,ordinalencoder,True,True,False,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",3.0,18,3,21,0.855,0.249,0.839,0.385,0.930,0.851,0.249,0.839,0.385,0.930,0.855,0.171,0.769,0.285,0.860
4,run_015,robust_scaler,ordinalencoder,True,True,False,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",3.0,18,3,21,0.810,0.315,0.885,0.454,0.929,0.812,0.320,0.887,0.459,0.929,0.809,0.197,0.811,0.316,0.853
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,run_019,custom_transformer,ordinalencoder,True,True,False,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,18,3,21,0.588,0.498,0.941,0.539,0.831,0.595,0.504,0.942,0.546,0.837,0.587,0.217,0.864,0.317,0.780
62,run_017,custom_transformer,onehotencoder,True,True,False,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,18,3,25,0.875,0.163,0.728,0.275,0.828,0.879,0.164,0.728,0.277,0.831,0.872,0.127,0.669,0.221,0.766
63,run_047,sqrt_transformer,ordinalencoder,True,True,True,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,39,0.611,0.685,0.960,0.646,0.826,0.610,0.680,0.960,0.643,0.825,0.612,0.252,0.881,0.357,0.781
64,run_041,custom_transformer,onehotencoder,True,True,True,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,43,0.695,0.368,0.912,0.482,0.810,0.701,0.372,0.912,0.486,0.813,0.694,0.204,0.837,0.315,0.769
65,run_044,custom_transformer,ordinalencoder,False,False,True,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,39,0.679,0.404,0.922,0.507,0.808,0.687,0.408,0.923,0.512,0.812,0.680,0.212,0.846,0.323,0.768