# Logistic Regression Preprocessing Benchmark
Non-AdaBoost logistic baseline using the shared preprocessing benchmark framework.

In [4]:
from preprocessing_benchmark_framework import (
    print_best_model_metrics,
    run_preprocessing_benchmark,
)

results_df, strategy_artifacts, top_per_metric, top_scores_df, top_combined, _ = run_preprocessing_benchmark(
    model_type='logistic',
    variant='default',
    output_dir_name='logistic',
    run_randomized=True,
    run_explicit=False,
    n_random_iterations_override=2,
    use_imbalance_options=False,
    balance_classes_before_training=True,
    total_threads=16,
    num_current_notebooks=4,
    add_polynomial=True,
    score_priority=['recall', 'precission', 'accuracy', 'f1', 'ROC-AUC'],
    top_n=25,
    metrics_to_save=['recall', 'precision', 'accuracy', 'f1', 'roc_auc'],
)

Saved recall best model -> /home/lelandmesford/Projects/Consumer_Habits/HospitalClinicalDeterioration/logistic/logistic_outliers_False_robust_scaler_onehotencoder_best_recall.joblib
Saved precision best model -> /home/lelandmesford/Projects/Consumer_Habits/HospitalClinicalDeterioration/logistic/logistic_outliers_False_robust_scaler_onehotencoder_best_precision.joblib
Saved accuracy best model -> /home/lelandmesford/Projects/Consumer_Habits/HospitalClinicalDeterioration/logistic/logistic_outliers_False_robust_scaler_onehotencoder_best_accuracy.joblib
Saved f1 best model -> /home/lelandmesford/Projects/Consumer_Habits/HospitalClinicalDeterioration/logistic/logistic_outliers_False_robust_scaler_onehotencoder_best_f1.joblib
Saved roc_auc best model -> /home/lelandmesford/Projects/Consumer_Habits/HospitalClinicalDeterioration/logistic/logistic_outliers_False_robust_scaler_onehotencoder_best_roc_auc.joblib

In [5]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None) 


priority = ['recall', 'precision', 'accuracy', 'f1', 'roc_auc']

print_best_model_metrics(results_df, metrics_to_show=priority)

print('Top score per metric (top-1 by metric):')
display(top_scores_df)

print('Combined top-N shortlist (deduplicated, sorted by ROC-AUC):')
display(top_combined)

Best model by test_recall:
config=num=robust_scaler, cat=onehotencoder, outliers=False, squared=False, cubed=False
best_params={'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.834      0.299     0.875 0.440    0.937
   test   0.834      0.301     0.876 0.442    0.937

Best model by test_precision:
config=num=robust_scaler, cat=onehotencoder, outliers=False, squared=False, cubed=False
best_params={'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.834      0.299     0.875 0.440    0.937
   test   0.834      0.301     0.876 0.442    0.937

Best model by test_accuracy:
config=num=robust_scaler, cat=onehotencoder, outliers=False, squared=False, cubed=False
best_params={'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.834      0.299     0.875 0.440    0.937
   test   0.834      0.301     0.876 0.442    0.937

Best model by test_f1:
config=num=robust_scaler, cat=onehotencoder, outliers=False, squared=False, cubed=False
best_params={'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.834      0.299     0.875 0.440    0.937
   test   0.834      0.301     0.876 0.442    0.937

Best model by test_roc_auc:
config=num=robust_scaler, cat=onehotencoder, outliers=False, squared=False, cubed=False
best_params={'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.834      0.299     0.875 0.440    0.937
   test   0.834      0.301     0.876 0.442    0.937
Top score per metric (top-1 by metric):

,metric,run_id,numeric_transformer,categorical_transformer,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,recall,run_001,robust_scaler,onehotencoder,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,25,0.834,0.299,0.875,0.44,0.937,0.834,0.301,0.876,0.442,0.937,0.834,0.192,0.802,0.312,0.855
1,precision,run_001,robust_scaler,onehotencoder,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,25,0.834,0.299,0.875,0.44,0.937,0.834,0.301,0.876,0.442,0.937,0.834,0.192,0.802,0.312,0.855
2,accuracy,run_001,robust_scaler,onehotencoder,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,25,0.834,0.299,0.875,0.44,0.937,0.834,0.301,0.876,0.442,0.937,0.834,0.192,0.802,0.312,0.855
3,f1,run_001,robust_scaler,onehotencoder,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,25,0.834,0.299,0.875,0.44,0.937,0.834,0.301,0.876,0.442,0.937,0.834,0.192,0.802,0.312,0.855
4,roc_auc,run_001,robust_scaler,onehotencoder,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,25,0.834,0.299,0.875,0.44,0.937,0.834,0.301,0.876,0.442,0.937,0.834,0.192,0.802,0.312,0.855

Combined top-N shortlist (deduplicated, sorted by ROC-AUC):

,run_id,numeric_transformer,categorical_transformer,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,run_001,robust_scaler,onehotencoder,False,False,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,18,3,25,0.834,0.299,0.875,0.440,0.937,0.834,0.301,0.876,0.442,0.937,0.834,0.192,0.802,0.312,0.855
1,run_002,robust_scaler,onehotencoder,False,True,False,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.836,0.297,0.873,0.438,0.936,0.834,0.296,0.873,0.437,0.937,0.832,0.194,0.803,0.314,0.865
2,run_004,robust_scaler,onehotencoder,False,True,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,54,3,61,0.825,0.296,0.874,0.436,0.933,0.825,0.296,0.874,0.435,0.933,0.820,0.189,0.800,0.308,0.852
3,run_003,robust_scaler,onehotencoder,False,False,True,"{'C': 0.1, 'class_weight': None, 'max_iter': 1000, 'random_state': 42, 'solver': 'liblinear'}","{'solver': 'liblinear', 'random_state': 42, 'max_iter': 1000, 'class_weight': None, 'C': 0.1}",1.5,36,3,43,0.816,0.298,0.876,0.437,0.928,0.818,0.299,0.876,0.438,0.930,0.812,0.190,0.802,0.308,0.848