# AdaBoost (Perceptron Base Estimator) Preprocessing Benchmark

In [ ]:
from preprocessing_benchmark_framework import (
    print_best_model_metrics,
    run_preprocessing_benchmark,
)

results_df, strategy_artifacts, top_per_metric, top_scores_df, top_combined, _ = run_preprocessing_benchmark(
    model_type='adaboost',
    variant='perceptron',
    output_dir_name='adaboost_perceptron',
    run_randomized=True,
    run_explicit=False,
    n_random_iterations_override=2,
    use_imbalance_options=False,
    balance_classes_before_training=True,
    total_threads=16,
    num_current_notebooks=4,
    iqr_multiplier=3.0,
    add_polynomial=True,
    score_priority=['recall', 'precision', 'accuracy', 'f1', 'ROC-AUC'],
    top_n=25,
    metrics_to_save=[],
)

In [ ]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_columns", None)   # show all columns
pd.set_option("display.max_colwidth", None) # show full column content

priority = ['recall', 'precision', 'accuracy', 'f1', 'roc_auc']

print_best_model_metrics(results_df, metrics_to_show=priority)

print('Top score per metric (top-1 by metric):')
display(top_scores_df)

print('Combined top-N shortlist (deduplicated, sorted by ROC-AUC):')
display(top_combined)

Best model by test_recall:
config=num=sqrt_transformer, cat=onehotencoder, outliers=True, squared=False, cubed=True
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.783      0.350     0.901 0.483    0.884
   test   0.788      0.352     0.902 0.487    0.886

Best model by test_precision:
config=num=sqrt_transformer, cat=onehotencoder, outliers=True, squared=True, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.702      0.522     0.944 0.598    0.918
   test   0.703      0.517     0.944 0.596    0.917

Best model by test_accuracy:
config=num=sqrt_transformer, cat=onehotencoder, outliers=True, squared=True, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.702      0.522     0.944 0.598    0.918
   test   0.703      0.517     0.944 0.596    0.917

Best model by test_f1:
config=num=sqrt_transformer, cat=onehotencoder, outliers=True, squared=True, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.702      0.522     0.944 0.598    0.918
   test   0.703      0.517     0.944 0.596    0.917

Best model by test_roc_auc:
config=num=sqrt_transformer, cat=onehotencoder, outliers=True, squared=True, cubed=True
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.774      0.381     0.912 0.510    0.922
   test   0.778      0.384     0.913 0.514    0.923
Top score per metric (top-1 by metric):

,metric,run_id,numeric_transformer,categorical_transformer,outliers_clipped,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,recall,run_003,sqrt_transformer,onehotencoder,True,True,False,True,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,43,0.783,0.350,0.901,0.483,0.884,0.788,0.352,0.902,0.487,0.886,0.781,0.206,0.825,0.326,0.810
1,precision,run_002,sqrt_transformer,onehotencoder,True,True,True,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,43,0.702,0.522,0.944,0.598,0.918,0.703,0.517,0.944,0.596,0.917,0.698,0.242,0.866,0.360,0.846
2,accuracy,run_002,sqrt_transformer,onehotencoder,True,True,True,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,43,0.702,0.522,0.944,0.598,0.918,0.703,0.517,0.944,0.596,0.917,0.698,0.242,0.866,0.360,0.846
3,f1,run_002,sqrt_transformer,onehotencoder,True,True,True,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,43,0.702,0.522,0.944,0.598,0.918,0.703,0.517,0.944,0.596,0.917,0.698,0.242,0.866,0.360,0.846
4,roc_auc,run_004,sqrt_transformer,onehotencoder,True,True,True,True,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",3.0,54,3,61,0.774,0.381,0.912,0.510,0.922,0.778,0.384,0.913,0.514,0.923,0.771,0.215,0.835,0.336,0.856

Combined top-N shortlist (deduplicated, sorted by ROC-AUC):

,run_id,numeric_transformer,categorical_transformer,outliers_clipped,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,run_004,sqrt_transformer,onehotencoder,True,True,True,True,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",3.0,54,3,61,0.774,0.381,0.912,0.510,0.922,0.778,0.384,0.913,0.514,0.923,0.771,0.215,0.835,0.336,0.856
1,run_001,sqrt_transformer,onehotencoder,True,True,False,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,18,3,25,0.749,0.417,0.923,0.536,0.920,0.753,0.416,0.923,0.536,0.920,0.748,0.225,0.847,0.346,0.848
2,run_002,sqrt_transformer,onehotencoder,True,True,True,False,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,43,0.702,0.522,0.944,0.598,0.918,0.703,0.517,0.944,0.596,0.917,0.698,0.242,0.866,0.360,0.846
3,run_003,sqrt_transformer,onehotencoder,True,True,False,True,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",3.0,36,3,43,0.783,0.350,0.901,0.483,0.884,0.788,0.352,0.902,0.487,0.886,0.781,0.206,0.825,0.326,0.810