# AdaBoost (MLP Base Estimator) Preprocessing Benchmark
Runtime is constrained with smaller randomized iterations for tractability.

In [5]:
from preprocessing_benchmark_framework import (
    print_best_model_metrics,
    run_preprocessing_benchmark,
)

results_df, strategy_artifacts, top_per_metric, top_scores_df, top_combined, _ = run_preprocessing_benchmark(
    model_type='adaboost',
    variant='logistic',
    output_dir_name='adaboost_mlp',
    run_randomized=True,
    run_explicit=False,
    n_random_iterations_override=2,
    use_imbalance_options=False,
    balance_classes_before_training=True,
    total_threads=16,
    num_current_notebooks=4,
    max_train_observations=5000,
    add_polynomial=True,
    score_priority=['recall', 'precision', 'accuracy', 'f1', 'ROC-AUC'],
    top_n=25,
    metrics_to_save=['recall', 'precision', 'accuracy', 'f1', 'roc_auc'],
)

ValueError:
All the 6 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "/home/lelandmesford/Projects/Consumer_Habits/.venv/lib/python3.13/site-packages/sklearn/model_selection/_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lelandmesford/Projects/Consumer_Habits/.venv/lib/python3.13/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/lelandmesford/Projects/Consumer_Habits/.venv/lib/python3.13/site-packages/sklearn/ensemble/_weight_boosting.py", line 167, in fit
    sample_weight, estimator_weight, estimator_error = self._boost(
                                                       ~~~~~~~~~~~^
        iboost, X, y, sample_weight, random_state
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lelandmesford/Projects/Consumer_Habits/.venv/lib/python3.13/site-packages/sklearn/ensemble/_weight_boosting.py", line 550, in _boost
    raise ValueError(
    ...<3 lines>...
    )
ValueError: BaseClassifier in AdaBoostClassifier ensemble is worse than random, ensemble can not be fit.

In [ ]:
priority = ['recall', 'precision', 'accuracy', 'f1', 'roc_auc']

print_best_model_metrics(results_df, metrics_to_show=priority)
import pandas as pd
pd.set_option("display.max_columns", None)   # show all columns
pd.set_option("display.max_colwidth", None) # show full column content

print('Top score per metric (top-1 by metric):')
display(top_scores_df)

print('Combined top-N shortlist (deduplicated, sorted by ROC-AUC):')
display(top_combined)

Best model by test_recall:
config=num=power_transformer, cat=ordinalencoder, outliers=False, squared=True, cubed=True
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.860      0.197     0.785 0.321    0.878
   test   0.857      0.198     0.786 0.321    0.881

Best model by test_precision:
config=num=power_transformer, cat=ordinalencoder, outliers=False, squared=True, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.829      0.228     0.824 0.358    0.908
   test   0.835      0.231     0.826 0.361    0.910

Best model by test_accuracy:
config=num=power_transformer, cat=ordinalencoder, outliers=False, squared=True, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.829      0.228     0.824 0.358    0.908
   test   0.835      0.231     0.826 0.361    0.910

Best model by test_f1:
config=num=power_transformer, cat=ordinalencoder, outliers=False, squared=True, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.829      0.228     0.824 0.358    0.908
   test   0.835      0.231     0.826 0.361    0.910

Best model by test_roc_auc:
config=num=power_transformer, cat=ordinalencoder, outliers=False, squared=True, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.829      0.228     0.824 0.358    0.908
   test   0.835      0.231     0.826 0.361    0.910
Top score per metric (top-1 by metric):

,metric,run_id,numeric_transformer,categorical_transformer,outliers_clipped,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,recall,run_004,power_transformer,ordinalencoder,False,False,True,True,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,54,3,57,0.860,0.197,0.785,0.321,0.878,0.857,0.198,0.786,0.321,0.881,0.855,0.145,0.719,0.248,0.829
1,precision,run_002,power_transformer,ordinalencoder,False,False,True,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,36,3,39,0.829,0.228,0.824,0.358,0.908,0.835,0.231,0.826,0.361,0.910,0.828,0.159,0.755,0.267,0.846
2,accuracy,run_002,power_transformer,ordinalencoder,False,False,True,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,36,3,39,0.829,0.228,0.824,0.358,0.908,0.835,0.231,0.826,0.361,0.910,0.828,0.159,0.755,0.267,0.846
3,f1,run_002,power_transformer,ordinalencoder,False,False,True,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,36,3,39,0.829,0.228,0.824,0.358,0.908,0.835,0.231,0.826,0.361,0.910,0.828,0.159,0.755,0.267,0.846
4,roc_auc,run_002,power_transformer,ordinalencoder,False,False,True,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,36,3,39,0.829,0.228,0.824,0.358,0.908,0.835,0.231,0.826,0.361,0.910,0.828,0.159,0.755,0.267,0.846

Combined top-N shortlist (deduplicated, sorted by ROC-AUC):

,run_id,numeric_transformer,categorical_transformer,outliers_clipped,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,run_002,power_transformer,ordinalencoder,False,False,True,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,36,3,39,0.829,0.228,0.824,0.358,0.908,0.835,0.231,0.826,0.361,0.910,0.828,0.159,0.755,0.267,0.846
1,run_003,power_transformer,ordinalencoder,False,False,False,True,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",1.5,36,3,39,0.829,0.220,0.816,0.348,0.904,0.829,0.220,0.817,0.348,0.902,0.828,0.155,0.747,0.261,0.844
2,run_001,power_transformer,ordinalencoder,False,False,False,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,18,3,21,0.822,0.221,0.818,0.348,0.893,0.822,0.222,0.819,0.350,0.894,0.822,0.156,0.750,0.262,0.828
3,run_004,power_transformer,ordinalencoder,False,False,True,True,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,54,3,57,0.860,0.197,0.785,0.321,0.878,0.857,0.198,0.786,0.321,0.881,0.855,0.145,0.719,0.248,0.829