# AdaBoost (Logistic Regression Base Estimator) Preprocessing Benchmark

In [ ]:
from preprocessing_benchmark_framework import (
    print_best_model_metrics,
    run_preprocessing_benchmark,
)

results_df, strategy_artifacts, top_per_metric, top_scores_df, top_combined, _ = run_preprocessing_benchmark(
    model_type='adaboost',
    variant='logistic',
    output_dir_name='adaboost_logistic',
    run_randomized=True,
    run_explicit=False,
    n_random_iterations_override=2,
    use_imbalance_options=False,
    balance_classes_before_training=True,
    total_threads=16,
    num_current_notebooks=4,
    add_polynomial=True,
    score_priority=['recall', 'precision', 'accuracy', 'f1', 'ROC-AUC'],
    top_n=25,
    metrics_to_save=['recall', 'precision', 'accuracy', 'f1', 'roc_auc'],
)

In [ ]:
priority = ['recall', 'precision', 'accuracy', 'f1', 'roc_auc']
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
print_best_model_metrics(results_df, metrics_to_show=priority)

print('Top score per metric (top-1 by metric):')
display(top_scores_df)

print('Combined top-N shortlist (deduplicated, sorted by ROC-AUC):')
display(top_combined)

Best model by test_recall:
config=num=robust_scaler, cat=onehotencoder, outliers=False, squared=True, cubed=True
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.845      0.256     0.846 0.393    0.908
   test   0.847      0.257     0.847 0.395    0.907

Best model by test_precision:
config=num=robust_scaler, cat=onehotencoder, outliers=False, squared=False, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.839      0.275     0.860 0.414    0.924
   test   0.840      0.278     0.861 0.417    0.924

Best model by test_accuracy:
config=num=robust_scaler, cat=onehotencoder, outliers=False, squared=False, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.839      0.275     0.860 0.414    0.924
   test   0.840      0.278     0.861 0.417    0.924

Best model by test_f1:
config=num=robust_scaler, cat=onehotencoder, outliers=False, squared=False, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.839      0.275     0.860 0.414    0.924
   test   0.840      0.278     0.861 0.417    0.924

Best model by test_roc_auc:
config=num=robust_scaler, cat=onehotencoder, outliers=False, squared=False, cubed=False
best_params={'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}
dataset  recall  precision  accuracy    f1  roc_auc
  train   0.839      0.275     0.860 0.414    0.924
   test   0.840      0.278     0.861 0.417    0.924
Top score per metric (top-1 by metric):

,metric,run_id,numeric_transformer,categorical_transformer,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,recall,run_004,robust_scaler,onehotencoder,False,True,True,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,54,3,61,0.845,0.256,0.846,0.393,0.908,0.847,0.257,0.847,0.395,0.907,0.843,0.174,0.775,0.288,0.855
1,precision,run_001,robust_scaler,onehotencoder,False,False,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,18,3,25,0.839,0.275,0.860,0.414,0.924,0.840,0.278,0.861,0.417,0.924,0.838,0.182,0.788,0.299,0.844
2,accuracy,run_001,robust_scaler,onehotencoder,False,False,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,18,3,25,0.839,0.275,0.860,0.414,0.924,0.840,0.278,0.861,0.417,0.924,0.838,0.182,0.788,0.299,0.844
3,f1,run_001,robust_scaler,onehotencoder,False,False,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,18,3,25,0.839,0.275,0.860,0.414,0.924,0.840,0.278,0.861,0.417,0.924,0.838,0.182,0.788,0.299,0.844
4,roc_auc,run_001,robust_scaler,onehotencoder,False,False,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,18,3,25,0.839,0.275,0.860,0.414,0.924,0.840,0.278,0.861,0.417,0.924,0.838,0.182,0.788,0.299,0.844

Combined top-N shortlist (deduplicated, sorted by ROC-AUC):

,run_id,numeric_transformer,categorical_transformer,outliers_enabled,use_squared,use_cubed,model_params,best_params,iqr_multiplier,n_numeric_cols,n_categorical_cols,n_transformed_features,train_recall,train_precision,train_accuracy,train_f1,train_roc_auc,test_recall,test_precision,test_accuracy,test_f1,test_roc_auc,joined_recall,joined_precision,joined_accuracy,joined_f1,joined_roc_auc
0,run_001,robust_scaler,onehotencoder,False,False,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,18,3,25,0.839,0.275,0.860,0.414,0.924,0.840,0.278,0.861,0.417,0.924,0.838,0.182,0.788,0.299,0.844
1,run_003,robust_scaler,onehotencoder,False,False,True,"{'learning_rate': 1.0, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 1.0}",1.5,36,3,43,0.821,0.240,0.836,0.371,0.919,0.823,0.241,0.837,0.373,0.919,0.819,0.165,0.767,0.275,0.871
2,run_002,robust_scaler,onehotencoder,False,True,False,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,36,3,43,0.845,0.264,0.852,0.403,0.918,0.846,0.265,0.852,0.403,0.917,0.844,0.178,0.781,0.294,0.860
3,run_004,robust_scaler,onehotencoder,False,True,True,"{'learning_rate': 0.5, 'n_estimators': 40, 'random_state': 42}","{'random_state': 42, 'n_estimators': 40, 'learning_rate': 0.5}",1.5,54,3,61,0.845,0.256,0.846,0.393,0.908,0.847,0.257,0.847,0.395,0.907,0.843,0.174,0.775,0.288,0.855