# AdaBoost (SVC Base Estimator) Preprocessing Benchmark
SVC variant uses reduced random iterations to keep runtime tractable.

In [2]:
from preprocessing_benchmark_framework import (
    print_best_model_metrics,
    run_preprocessing_benchmark,
)

results_df, strategy_artifacts, top_per_metric, top_scores_df, top_combined, _ = run_preprocessing_benchmark(
    model_type='adaboost',
    variant='svc',
    output_dir_name='adaboost_svc',
    run_randomized=True,
    run_explicit=False,
    n_random_iterations_override=2,
    use_imbalance_options=False,
    balance_classes_before_training=True,
    total_threads=16,
    num_current_notebooks=2,
    iqr_multiplier=3.0,
    max_train_observations=5000,
    add_polynomial=True,
    score_priority=['recall', 'precision', 'accuracy', 'f1', 'ROC-AUC'],
    top_n=25,
    metrics_to_save=['recall', 'precision', 'accuracy', 'f1', 'roc_auc'],
)

:

In [ ]:
priority = ['recall', 'precision', 'accuracy', 'f1', 'roc_auc']

print_best_model_metrics(results_df, metrics_to_show=priority)
import pandas as pd
pd.set_option("display.max_columns", None)   # show all columns
pd.set_option("display.max_colwidth", None) # show full column content

print('Top score per metric (top-1 by metric):')
display(top_scores_df)

print('Combined top-N shortlist (deduplicated, sorted by ROC-AUC):')
display(top_combined)

,run_id,model_type,variant,numeric_transformer,categorical_transformer,outliers_enabled,best_params,train_size_reduction_factor,actual_train_size,recall,precision,accuracy,f1,roc_auc
20,run_021,adaboost,svc,sqrt_transformer,onehotencoder,True,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.793935,0.133460,0.683427,0.228508,0.735214
12,run_013,adaboost,svc,robust_scaler,onehotencoder,True,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.787295,0.186925,0.785218,0.302119,0.786191
5,run_006,adaboost,svc,power_transformer,onehotencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.779327,0.224812,0.828284,0.348959,0.805342
4,run_005,adaboost,svc,power_transformer,onehotencoder,True,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.777778,0.227179,0.830637,0.351646,0.805866
7,run_008,adaboost,svc,power_transformer,ordinalencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.736830,0.222438,0.832362,0.341716,0.787594

,run_id,model_type,variant,numeric_transformer,categorical_transformer,outliers_enabled,best_params,train_size_reduction_factor,actual_train_size,recall,precision,accuracy,f1,roc_auc
4,run_005,adaboost,svc,power_transformer,onehotencoder,True,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.777778,0.227179,0.830637,0.351646,0.805866
13,run_014,adaboost,svc,robust_scaler,onehotencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.612660,0.225169,0.852634,0.329308,0.740177
5,run_006,adaboost,svc,power_transformer,onehotencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.779327,0.224812,0.828284,0.348959,0.805342
6,run_007,adaboost,svc,power_transformer,ordinalencoder,True,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.736166,0.223311,0.833224,0.342675,0.787741
7,run_008,adaboost,svc,power_transformer,ordinalencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.736830,0.222438,0.832362,0.341716,0.787594

,run_id,model_type,variant,numeric_transformer,categorical_transformer,outliers_enabled,best_params,train_size_reduction_factor,actual_train_size,recall,precision,accuracy,f1,roc_auc
15,run_016,adaboost,svc,robust_scaler,ordinalencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.547809,0.212100,0.853130,0.305801,0.710050
13,run_014,adaboost,svc,robust_scaler,onehotencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.612660,0.225169,0.852634,0.329308,0.740177
21,run_022,adaboost,svc,sqrt_transformer,onehotencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.492475,0.197725,0.852032,0.282163,0.683536
23,run_024,adaboost,svc,sqrt_transformer,ordinalencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.506640,0.181927,0.836335,0.267719,0.681833
6,run_007,adaboost,svc,power_transformer,ordinalencoder,True,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.736166,0.223311,0.833224,0.342675,0.787741

,run_id,model_type,variant,numeric_transformer,categorical_transformer,outliers_enabled,best_params,train_size_reduction_factor,actual_train_size,recall,precision,accuracy,f1,roc_auc
4,run_005,adaboost,svc,power_transformer,onehotencoder,True,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.777778,0.227179,0.830637,0.351646,0.805866
5,run_006,adaboost,svc,power_transformer,onehotencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.779327,0.224812,0.828284,0.348959,0.805342
6,run_007,adaboost,svc,power_transformer,ordinalencoder,True,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.736166,0.223311,0.833224,0.342675,0.787741
7,run_008,adaboost,svc,power_transformer,ordinalencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.736830,0.222438,0.832362,0.341716,0.787594
13,run_014,adaboost,svc,robust_scaler,onehotencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.612660,0.225169,0.852634,0.329308,0.740177

,run_id,model_type,variant,numeric_transformer,categorical_transformer,outliers_enabled,best_params,train_size_reduction_factor,actual_train_size,recall,precision,accuracy,f1,roc_auc
4,run_005,adaboost,svc,power_transformer,onehotencoder,True,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.777778,0.227179,0.830637,0.351646,0.805866
5,run_006,adaboost,svc,power_transformer,onehotencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.779327,0.224812,0.828284,0.348959,0.805342
6,run_007,adaboost,svc,power_transformer,ordinalencoder,True,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.736166,0.223311,0.833224,0.342675,0.787741
7,run_008,adaboost,svc,power_transformer,ordinalencoder,False,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.736830,0.222438,0.832362,0.341716,0.787594
12,run_013,adaboost,svc,robust_scaler,onehotencoder,True,"{'random_state': 42, 'n_estimators': 20, 'lear...",0.15,45905,0.787295,0.186925,0.785218,0.302119,0.786191